// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUVLVE1xN0tjb0JxMmlOOFpDM2JPNVRIcU1pZGNyRFhZOFZpblB1ZXRFND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSFcrNTRKQjVNSjAvUzh1OXk0ajhMUjhQem5pbS95ODVua2UxYjZzQXFIND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRTlczd0RVWmFqTFVxN2lQQ3dXaWpvK1RrQ25Wcmo4NDBjM0tFY1cvNVVFPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4cWpZZWpIK3ZZQUpLQXpjd0crSGxqYnlOYmExZFM3TzJEaUFCSmZ4UzBZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtDN1U5TnRvUHdNNklpc05namNBc3kycnBmaVY1bTVqU2hNaTBvR0owVWc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InZ6T1dULzNid053N2VMRUFKaERMSkEzNWlNamIvLys3NW5ZZzBSOUhUVkE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWU9yYTJtVDZqc1NQL3VHWlUvTnNVYXZvS1kwOTJuMGdsUDkvWklicnNuRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMnJxVCtvVFFEVFJtSW80VG5GTUZSVWZJbmF6WFJIMUJLRnRMWEZJZE0wZz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjlZazc3ZUpXZHFsU24xQmVNY2J3dExXckZVMFJFOHdiUmVuV3J2bTBlNnBuSnRRUE1hR2huanRhdWM3aHg3OFYvZTJuZVB6UXdWMjNDOGwzNHZVN0R3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTUsImFkdlNlY3JldEtleSI6IjhZMG1BYzhSa2dGS0dNcEZVdTRiK04vUHJQbzBRN2gvVjU2L0doODhrd2s9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IkZUa1laRE53VGpPVEYzTmMzekpwX1EiLCJwaG9uZUlkIjoiMTVkY2QxNzktZWE2YS00MDI4LTg1MDItMDM3OTE0NDNlM2MxIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVKNy92QjJjb1FRNk9EcHhaS2xqVWJUb0R4ST0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJPcFFaYkJONzY4TUNDUFRWWkFLVE5lSlE3YTg9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiUzRFQzlIS1kiLCJtZSI6eyJpZCI6IjI1NDc5NzY2Njc1MDoxNkBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUHZSdkxnSEVKT0N2TG9HR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiUFpRK29YVnQ1eXh6bzNqY0FjL2JVQkFadFp0UGw3ZFhsMTg5cm9SeHpWdz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiUUlnSXVmZ2FSMXF2SzZhY3g0NFpEb2JzdlFXTTF1MkxWcmFLcXF4VVhxWHRoVHFLT0VrbmF6N2VZTlRGdEM0VTN6OUNTQkorWmsvL1pTb04rUDI1RHc9PSIsImRldmljZVNpZ25hdHVyZSI6ImdwUTAwVnVpRkJ0S2U0NmdyZXNKOHB3TnhMMVVzQXhrdzZkVlFuRFl4L0FnRDBWQy9oQjFhdjFBS2c1dnBidFlHTjd2bmljdHhqRW52cDBPMUlRV0NRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0Nzk3NjY2NzUwOjE2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlQyVVBxRjFiZWNzYzZONDNBSFAyMUFRR2JXYlQ1ZTNWNWRmUGE2RWNjMWMifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzMyMzA4ODB9",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "Bera",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "254743982206",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
